Add METER device
mpepping/solarman-mqtt pull request #98
Opened 2023-09-13 09:31 UTC by NameLessJedi

I've got DTSD422 meter added to my instalation. This patch allows to get additional info from it (note that it's normally available 24/7 also when Inverter is off)

2023-09-13 16:08 UTC, mpepping requested changes

2023-09-13 16:08 UTC, mpepping commented on solarman/helpers.py
> +        "metterId": {"type": "string", "minLength": 10},
Small typo here

2023-09-13 16:08 UTC, mpepping commented on solarman/solarmanpv.py
Pylint fails on the following. Can you push an update for that?

```
Run pylint -r yes run.py solarman
************* Module solarman.solarmanpv
solarman/solarmanpv.py:51:4: R0914: Too many local variables (17/15) (too-many-locals)
solarman/solarmanpv.py:51:4: R0912: Too many branches (18/12) (too-many-branches)
solarman/solarmanpv.py:51:4: R0915: Too many statements (60/50) (too-many-statements)
```

2023-09-13 16:08 UTC, mpepping commented on solarman/api.py
Pylint fails on the following. Can you push an update for that?

```
Run pylint -r yes run.py solarman
************* Module solarman.api
solarman/api.py:11:0: R0902: Too many instance attributes (8/7) (too-many-instance-attributes)
```

2023-09-13 16:12 UTC, mpepping commented
Thanks for the PR, @NameLessJedi. I've added some feedback here and there .. but looks good overall!

2023-09-19 10:55 UTC, NameLessJedi commented on solarman/solarmanpv.py
Actually I don't have a clue how to resolve this (and the one below about api.py too). Not without some excess (and I think not needed) rewriting of bigger chunks of code

2023-09-24 07:59 UTC, mpepping commented on solarman/solarmanpv.py
Fair enough. The current structure doesn't scale that well. It would be better to use a dict for the whole config in the api class.

2023-09-24 08:06 UTC, mpepping approved these changes

2023-09-24 08:11 UTC, merged

2023-09-24 08:12 UTC, mpepping commented
Thanks for the PR, @NameLessJedi! Merged!

2023-09-25 12:10 UTC, NameLessJedi commented
I've just realized that I forgot one thing. It's probably moot to open PR.
The deviceSn of Meter can be obtained like this:

```
curl --location --request POST 'https://globalapi.solarmanpv.com/station/v1.0/device?language=en' \
  --header 'Content-Type: application/json' \
  --header 'Authorization: bearer TOKEN' \
  --data-raw '{"size":10,"page":1,"stationId":1234567,"deviceType":"METER"}'
```

In my case it's identical to S/N number but with some additions. My meter device has S/N of 26xxxx and the deviceSn is 0026xxxx-001 (two 0 at the begining and -01 at the end).